name    'mrzarquon-pe_agent'
version '0.0.1'
source 'git@github.com:mrzarquon/mrzarquon-pe_agent.git'
author 'mrzarquon'
license 'Apache 2.0'
summary 'pe_agent configuration module'
description 'Handles the management of PE specific repositories, agent packages and configuration'
project_page 'https://github.com/mrzarquon/mrzarquon-pe_agent'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
